import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { Quicksand } from 'next/font/google';
import { cookies } from "next/headers";
import { fetchWithAuth } from "./utils/server.request";
import { User } from "./types/auth";

const quicksand = Quicksand({ 
  subsets: ['latin'],
  variable: '--font-quicksand',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get('token')?.value;

  let user: User | null = null;
  if (token) user = await fetchWithAuth<User>(`${process.env.NEXT_PUBLIC_API_URL}/auth/me`, token);
  
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} antialiased`}
      >
        <Providers initialUser={user}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
